version: "2"

services :
    drupal:
      build: ./drupal/
      ports:
        - "9000:80"
      volumes:
        - "./drupal/themes/:/var/www/html/themes"
      links:
        - db
      networks:
        - default

    data:
      build: ./data/
      command: /bin/true

    db:
       build: ./postgresql/
       ports:
         - "5499:5432"
       volumes_from:
         - data
       environment:
         PGDATA: /var/lib/postgresql/data
       networks:
         - default

networks:
  default:

